analyzer:
  exclude:
    - build/**
    - .dart_tool/**
  errors:
    invalid_assignment: error
    invalid_return_type: error
    missing_return: error
    dead_code: warning
    unused_import: warning
