create or replace function private.is_workspace_member(p_workspace_id uuid,p_user_id uuid default auth.uid()) returns boolean language sql stable security definer set search_path=public,private as $$ select exists(select 1 from public.workspace_members where workspace_id=p_workspace_id and user_id=p_user_id); $$;
create or replace function private.workspace_role(p_workspace_id uuid,p_user_id uuid default auth.uid()) returns text language sql stable security definer set search_path=public,private as $$ select role from public.workspace_members where workspace_id=p_workspace_id and user_id=p_user_id limit 1; $$;
create or replace function private.can_edit_workspace(p_workspace_id uuid,p_user_id uuid default auth.uid()) returns boolean language sql stable security definer set search_path=public,private as $$ select private.workspace_role(p_workspace_id,p_user_id) in ('owner','admin','member'); $$;
revoke all on function private.is_workspace_member(uuid,uuid),private.workspace_role(uuid,uuid),private.can_edit_workspace(uuid,uuid) from public,anon,authenticated;
grant usage on schema private to authenticated;
grant execute on function private.is_workspace_member(uuid,uuid),private.workspace_role(uuid,uuid),private.can_edit_workspace(uuid,uuid) to authenticated;
insert into public.workspace_members(workspace_id,user_id,role) select id,owner_id,'owner' from public.workspaces where not exists(select 1 from public.workspace_members wm where wm.workspace_id=workspaces.id and wm.user_id=workspaces.owner_id);
drop policy if exists workspaces_select_own on public.workspaces;
create policy workspaces_select_member on public.workspaces for select using(private.is_workspace_member(id));
drop policy if exists workspaces_update_own on public.workspaces;
create policy workspaces_update_admin on public.workspaces for update using(private.workspace_role(id) in ('owner','admin')) with check(private.workspace_role(id) in ('owner','admin'));
drop policy if exists workspaces_delete_own on public.workspaces;
create policy workspaces_delete_owner on public.workspaces for delete using(owner_id=auth.uid());
drop policy if exists missions_select_own on public.missions;
create policy missions_select_member on public.missions for select using(private.is_workspace_member(workspace_id));
drop policy if exists missions_insert_own on public.missions;
create policy missions_insert_member on public.missions for insert with check(owner_id=auth.uid() and private.can_edit_workspace(workspace_id));
drop policy if exists missions_update_own on public.missions;
create policy missions_update_editor on public.missions for update using(private.can_edit_workspace(workspace_id)) with check(private.can_edit_workspace(workspace_id));
drop policy if exists missions_delete_own on public.missions;
create policy missions_delete_admin on public.missions for delete using(private.workspace_role(workspace_id) in ('owner','admin'));
drop policy if exists mission_actions_select_own on public.mission_actions;
create policy mission_actions_select_member on public.mission_actions for select using(exists(select 1 from public.missions m where m.id=mission_actions.mission_id and private.is_workspace_member(m.workspace_id)));
drop policy if exists mission_actions_insert_own on public.mission_actions;
create policy mission_actions_insert_editor on public.mission_actions for insert with check(exists(select 1 from public.missions m where m.id=mission_actions.mission_id and private.can_edit_workspace(m.workspace_id)));
drop policy if exists mission_actions_update_own on public.mission_actions;
create policy mission_actions_update_editor on public.mission_actions for update using(exists(select 1 from public.missions m where m.id=mission_actions.mission_id and private.can_edit_workspace(m.workspace_id))) with check(exists(select 1 from public.missions m where m.id=mission_actions.mission_id and private.can_edit_workspace(m.workspace_id)));
drop policy if exists mission_actions_delete_own on public.mission_actions;
create policy mission_actions_delete_admin on public.mission_actions for delete using(exists(select 1 from public.missions m where m.id=mission_actions.mission_id and private.workspace_role(m.workspace_id) in ('owner','admin')));
drop policy if exists mission_events_select_own on public.mission_events;
create policy mission_events_select_member on public.mission_events for select using(private.is_workspace_member((select workspace_id from public.missions where id=mission_events.mission_id)));
drop policy if exists mission_verifications_select_own on public.mission_verifications;
create policy mission_verifications_select_member on public.mission_verifications for select using(private.is_workspace_member((select workspace_id from public.missions where id=mission_verifications.mission_id)));
drop policy if exists mission_outcomes_select_own on public.mission_outcomes;
create policy mission_outcomes_select_member on public.mission_outcomes for select using(private.is_workspace_member((select workspace_id from public.missions where id=mission_outcomes.mission_id)));
drop policy if exists workspace_members_select_member on public.workspace_members;
create policy workspace_members_select_member on public.workspace_members for select using(private.is_workspace_member(workspace_id));
drop policy if exists workspace_members_owner_manage on public.workspace_members;
create policy workspace_members_owner_manage on public.workspace_members for all using(exists(select 1 from public.workspaces w where w.id=workspace_members.workspace_id and w.owner_id=auth.uid())) with check(exists(select 1 from public.workspaces w where w.id=workspace_members.workspace_id and w.owner_id=auth.uid()));
drop policy if exists workspace_agents_member_select on public.workspace_agents;
create policy workspace_agents_member_select on public.workspace_agents for select using(private.is_workspace_member(workspace_id));
drop policy if exists workspace_agents_admin_manage on public.workspace_agents;
create policy workspace_agents_admin_manage on public.workspace_agents for all using(private.workspace_role(workspace_id) in ('owner','admin')) with check(private.workspace_role(workspace_id) in ('owner','admin'));
drop policy if exists mission_approvals_member_select on public.mission_approvals;
create policy mission_approvals_member_select on public.mission_approvals for select using(private.is_workspace_member(workspace_id));
drop policy if exists mission_approvals_member_insert on public.mission_approvals;
create policy mission_approvals_member_insert on public.mission_approvals for insert with check(private.is_workspace_member(workspace_id) and requested_by=auth.uid());
drop policy if exists mission_approvals_approver_update on public.mission_approvals;
create policy mission_approvals_approver_update on public.mission_approvals for update using(private.workspace_role(workspace_id) in ('owner','admin')) with check(private.workspace_role(workspace_id) in ('owner','admin'));
revoke all on public.workspace_members,public.workspace_agents,public.mission_approvals from anon;
grant select,insert,update,delete on public.workspace_members,public.workspace_agents,public.mission_approvals to authenticated;